const VK_CRUNCH = "https://vkvideo.ru/video-226154718_456239154";

const WEEK1_DAYS = [
  {
    title: "День 1 — Ноги",
    place: "Дом",
    exercises: [
      {
        muscle: "Ягодицы",
        name: "Плие",
        warmup: true,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Плоская лента", "Мини-бэнд"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Спина прямая, ноги шире плеч, носки слегка наружу. Плавно, без рывков.",
        videos: [],
      },
      {
        muscle: "Квадрицепсы",
        name: "Разгибания",
        warmup: true,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Плоская лента"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Лёжа на спине, резинка на стопах. Фиксация вверху 1–2 сек, медленный негатив.",
        videos: [],
      },
      {
        muscle: "Бицепс бедра",
        name: "Сгибания лёжа",
        warmup: true,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Плоская лента"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Лёжа на животе, сгибаем ноги к ягодицам, удерживаем 1–2 сек.",
        videos: [],
      },
      {
        muscle: "Ягодицы",
        name: "Разведения ног сидя",
        warmup: false,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Плоская лента", "Мини-бэнд"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Резинка выше колен, спина прямая, пик-сокращение 1–2 сек.",
        videos: [],
      },
      {
        muscle: "Пресс",
        name: "Скручивания",
        warmup: false,
        workSets: 2,
        reps: "15–30",
        rest: "60–120 сек",
        equipment: ["Масса тела"],
        intensity: "До жжения",
        notes: "Без рывков, внизу — растяжение, работаем до жжения.",
        videos: [{ label: "Скручивания — техника", href: VK_CRUNCH }],
      },
    ],
  },
  {
    title: "День 2 — Верх",
    place: "Дом",
    exercises: [
      {
        muscle: "Спина",
        name: "Вертикальная тяга на одну руку",
        warmup: true,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Плоская лента"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Фиксация ленты выше головы…",
        videos: [],
      },
      {
        muscle: "Грудь",
        name: "Жим лёжа",
        warmup: true,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Плоская лента", "Гантели (по желанию)"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Локти ~45°…",
        videos: [],
      },
      {
        muscle: "Спина",
        name: "Горизонтальная тяга",
        warmup: false,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Длинная петля", "Плоская лента"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Тянем к корпусу…",
        videos: [],
      },
      {
        muscle: "Грудь",
        name: "Сведение лёжа на грудь",
        warmup: false,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Плоская лента", "Гантели"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Слегка согнутые локти…",
        videos: [],
      },
      {
        muscle: "Пресс",
        name: "Скручивания",
        warmup: false,
        workSets: 3,
        reps: "15–30",
        rest: "60–120 сек",
        equipment: ["Масса тела"],
        intensity: "До жжения",
        notes: "Без рывков…",
        videos: [{ label: "Скручивания — техника", href: VK_CRUNCH }],
      },
    ],
  },
  {
    title: "День 3 — Ноги/Ягодицы",
    place: "Дом",
    exercises: [
      {
        muscle: "Ягодицы",
        name: "Ягодичный мостик",
        warmup: true,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Плоская лента", "Гантель на таз", "Мини-бэнд"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Колени ~90°, фиксация 1–2 сек…",
        videos: [],
      },
      {
        muscle: "Бицепс бедра",
        name: "Сгибания ног стоя",
        warmup: true,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Плоская лента", "Мини-бэнд"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Опора рукой…",
        videos: [],
      },
      {
        muscle: "Ягодицы",
        name: "Отведение ноги в сторону (на четвереньках)",
        warmup: true,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Плоская лента", "Мини-бэнд"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Лента выше колен…",
        videos: [],
      },
      {
        muscle: "Ягодицы",
        name: "Жим ногой на четвереньках",
        warmup: false,
        workSets: 3,
        reps: "12–15",
        rest: "60–120 сек",
        equipment: ["Плоская лента", "Мини-бэнд"],
        intensity: "Вблизи отказа (1–2 повт.)",
        notes: "Выпрямляем назад/вверх…",
        videos: [],
      },
      {
        muscle: "Пресс",
        name: "Скручивания",
        warmup: false,
        workSets: 1,
        reps: "15–30",
        rest: "60–120 сек",
        equipment: ["Масса тела"],
        intensity: "До жжения",
        notes: "До жжения…",
        videos: [{ label: "Скручивания — техника", href: VK_CRUNCH }],
      },
    ],
  },
];

const HOME_PROGRAMS = {
  S: { name: "Start", weeks: [
    { name: "Неделя 1", days: WEEK1_DAYS },
    { name: "Неделя 2", days: WEEK1_DAYS },
    { name: "Неделя 3", days: WEEK1_DAYS },
    { name: "Неделя 4", days: WEEK1_DAYS },
  ] },
  M: { name: "Medium", weeks: [] },
  P: { name: "Pro", weeks: [] },
};

export default HOME_PROGRAMS;
